[package]
name = "Encora"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20 = "0.9.1"
iced = { version = "0.12.1"}
rfd = "0.15.0"
rand ="0.8.5"
aes = "0.7"
block-modes = "0.8"  # Required for block modes like CBC
generic-array = "0.14"
